<?
$aMenuLinks = Array(
	Array(
		"Состояние и история", 
		"/personal/billing/", 
		Array(), 
		Array(), 
		"CSite::InGroup(array(1,12,13,14,15))" 
	),
	Array(
		"Договор", 
		"/personal/billing/dogovor.php", 
		Array(), 
		Array(), 
		"CSite::InGroup(array(1,12,13,14,15))" 
	),
	Array(
		"Акты", 
		"/personal/billing/akty.php", 
		Array(), 
		Array(), 
		"CSite::InGroup(array(1,12,13,14,15))" 
	),
	Array(
		"Клиенты", 
		"/personal/billing/klienty.php", 
		Array(), 
		Array(), 
		"CSite::InGroup(array(1,6))" 
	),
	Array(
		"Договора", 
		"/personal/billing/dogovora.php", 
		Array(), 
		Array(), 
		"CSite::InGroup(array(1,6))" 
	),
	Array(
		"Акты", 
		"/personal/billing/akty/", 
		Array(), 
		Array(), 
		"CSite::InGroup(array(1,6))" 
	),
	Array(
		"Счета", 
		"/personal/billing/vystavlennyescheta.php", 
		Array(), 
		Array(), 
		"CSite::InGroup(array(1,12,13,14,15))" 
	),
	Array(
		"Счета", 
		"/personal/billing/scheta.php", 
		Array(), 
		Array(), 
		"CSite::InGroup(array(1,6))" 
	)
);
?>