<?
$PERM["index.php"]["G3"]="R";
$PERM["index.php"]["G7"]="R";
$PERM["index.php"]["G6"]="R";
$PERM["index.php"]["*"]="D";
$PERM["support.php"]["*"]="D";
$PERM["support.php"]["10"]="R";
$PERM["support.php"]["9"]="R";
$PERM["cart"]["*"]="R";
?>